import os
os.environ["STREAMLIT_SERVER_FILE_WATCHER_TYPE"] = "none"

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

st.set_page_config(
    page_title="Cotizador Grupo Proservices 2026",
    page_icon="💰",
    layout="wide"
)

# =================================================================================
# MATRIZ DE MÁRGENES 2026
# El tramo se determina usando el PRECIO DE LISTA.
# =================================================================================
MARGENES = [
    {"Tramo": "$1 – $299.999", "Min": 1, "Max": 299999, "Margen": 0.22},
    {"Tramo": "$300.000 – $999.999", "Min": 300000, "Max": 999999, "Margen": 0.185},
    {"Tramo": "$1.000.000 – $1.999.999", "Min": 1_000_000, "Max": 1_999_999, "Margen": 0.18},
    {"Tramo": "$2.000.000 – $2.999.999", "Min": 2_000_000, "Max": 2_999_999, "Margen": 0.175},
    {"Tramo": "$3.000.000 – $4.999.999", "Min": 3_000_000, "Max": 4_999_999, "Margen": 0.17},
    {"Tramo": "SOBRE 5.000.000", "Min": 5_000_000, "Max": float("inf"), "Margen": 0.17},
]

# =================================================================================
# PROVEEDORES
# PGIC, KOSLAN, KSB, COSMOPLAS, FRANKLIN y HCP actualizados según matriz 17-08-2026.
# No se aplica ningún descuento adicional por monto.
# =================================================================================
PROVEEDORES = [{'Proveedor': 'LAS BRUJAS (EQUIPOS DE RIEGO)',
  'Marca': 'PROPUMPS VERTICAL',
  'Línea de Producto': 'Bombas multietapas verticales inox AISI 304',
  'Modelo Base': 'ECDLF',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.43,
  'Forma de Pago': 'Cheques 30 días',
  'Condición de pago por monto': 'sobre 1MM / 2 cheques/ sobre 2MM 3 cheques',
  'Garantía': '1 año',
  'Buscar Precio en': 'App LAS BRUJAS',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'JUAN CARLOS GUTIERREZ / +56 9 68319437',
  'Email': 'comunicacionesodoo@equiposderiego.cl',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: Bombas2024*',
  'Web/App proveedor': 'https://equiposderiego.b2bcarts.com/login'},
 {'Proveedor': 'LAS BRUJAS (EQUIPOS DE RIEGO)',
  'Marca': 'VAREM',
  'Línea de Producto': 'Estanques hidroneumáticos',
  'Modelo Base': 'VERTICAL / HORIZONTAL / 10BAR /16BAR',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Cheques 30 días',
  'Condición de pago por monto': 'sobre 1MM / 2 cheques/ sobre 2MM 3 cheques',
  'Garantía': '1 año',
  'Buscar Precio en': 'App LAS BRUJAS',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'JUAN CARLOS GUTIERREZ / +56 9 68319440',
  'Email': 'comunicacionesodoo@equiposderiego.cl',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: Bombas2024*',
  'Web/App proveedor': 'https://equiposderiego.b2bcarts.com/login'},
 {'Proveedor': 'LAS BRUJAS (EQUIPOS DE RIEGO)',
  'Marca': 'FORAS',
  'Línea de Producto': 'Bombas centrífugas, multietapas, drenaje',
  'Modelo Base': 'FV/FC/DC/NM/KB',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.42,
  'Forma de Pago': 'Cheques 30 días',
  'Condición de pago por monto': 'sobre 1MM / 2 cheques/ sobre 2MM 3 cheques',
  'Garantía': '1 año',
  'Buscar Precio en': 'App LAS BRUJAS',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'JUAN CARLOS GUTIERREZ / +56 9 68319441',
  'Email': 'comunicacionesodoo@equiposderiego.cl',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: Bombas2024*',
  'Web/App proveedor': 'https://equiposderiego.b2bcarts.com/login'},
 {'Proveedor': 'LAS BRUJAS (EQUIPOS DE RIEGO)',
  'Marca': 'PROPUMPS HORIZONTAL',
  'Línea de Producto': 'Bombas centrífugas, multietapas, drenaje',
  'Modelo Base': 'HFT/DP/SCM/CM2',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.36,
  'Forma de Pago': 'Cheques 30 días',
  'Condición de pago por monto': 'sobre 1MM / 2 cheques/ sobre 2MM 3 cheques',
  'Garantía': '1 año',
  'Buscar Precio en': 'App LAS BRUJAS',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'JUAN CARLOS GUTIERREZ / +56 9 68319442',
  'Email': 'comunicacionesodoo@equiposderiego.cl',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: Bombas2024*',
  'Web/App proveedor': 'https://equiposderiego.b2bcarts.com/login'},
 {'Proveedor': 'PGIC',
  'Marca': 'CALPEDA',
  'Línea de Producto': 'Bombas multietapa horizontal inox AISI 304',
  'Modelo Base': 'MXHM / MXH',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'STAIRS',
  'Línea de Producto': 'Bombas sumergibles pozo profundo',
  'Modelo Base': '6SP / 4ST / 8SP',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'STAIRS',
  'Línea de Producto': 'Bombas multietapa vertical inox AISI 304',
  'Modelo Base': 'SB / SBI',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.43,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '2 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0190',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5679',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'AQUASYSTEM',
  'Línea de Producto': 'Estanques hidroneumáticos ',
  'Modelo Base': 'VERTICAL / HORIZONTAL / 10BAR /16BAR',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'CALPEDA',
  'Línea de Producto': 'Bombas de superficie italianas',
  'Modelo Base': 'CENTRIFUGA / PERIFERICA / NORMALIZADA / EJE LIBRE',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'MEUDY',
  'Línea de Producto': 'Bombas sumergibles para lodo /contratistas',
  'Modelo Base': 'FSM/ KSM /KBZ /KBS/ KBD',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'MEUDY',
  'Línea de Producto': 'Bombas sumergibles aguas servidas',
  'Modelo Base': 'U / C /B /G',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'BESTFLOW',
  'Línea de Producto': 'Bombas de pozo / superficie / Variadores y tableros eléctricos',
  'Modelo Base': 'VFD / TBF / STAR',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'DRENO',
  'Línea de Producto': 'Bombas para aguas servidas y drenaje',
  'Modelo Base': 'AM / AT /COMPATTA',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'FRANKLIN',
  'Línea de Producto': 'Motores sumergibles y bombas STAIRS by Franklin',
  'Modelo Base': '4FM / 6FM',
  'Procedencia': 'EE.UU. ',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'SUBLINE',
  'Línea de Producto': 'Bombas sumergibles de pozo',
  'Modelo Base': 'FF / FS',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'ELENTEK',
  'Línea de Producto': 'Tableros eléctricos inteligentes y arrancadores',
  'Modelo Base': 'TABLEROS CONTROL ELECTRONICOS',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.36,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'ULMAX',
  'Línea de Producto': 'Bombas verticales multietapas / Variadores de frecuencia',
  'Modelo Base': 'SVMT',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'ULMAX',
  'Línea de Producto': ' Variadores de frecuencia',
  'Modelo Base': 'UX ',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.42,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'REGGIO',
  'Línea de Producto': 'Bombas centrífugas, multietapas, drenaje',
  'Modelo Base': 'SM / ST /CFM / STF /STO /SSBJ',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'PGIC',
  'Marca': 'REGGIO',
  'Línea de Producto': 'Bombas centrífugas Normalizadas',
  'Modelo Base': 'SN',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.5,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App PGIC',
  'Entrega con despacho': '1 día hábil',
  'Contacto Vendedor': 'Valeska Canales / +56 9 6206 0189',
  'Email': 'vcanales@pgic.cl',
  'Web/App proveedor': 'https://b2b.pgic.cl',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: Kimberly / Clave: Operaciones24 / Ver precios en app PGIC',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'PEDROLLO',
  'Línea de Producto': 'Bombas superficie ',
  'Modelo Base': 'CPM /CP / 2CPM / HF / F',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.45,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '3 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8608',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'ID Cliente: 1739',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'PEDROLLO',
  'Línea de Producto': 'Bombas sumergible / pozo / aguas servidas / drenaje',
  'Modelo Base': '4SR /4BLOCK /VX /MC ',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '3 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8609',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'ID Cliente: 1739',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'PEDROLLO',
  'Línea de Producto': 'Variadores y tableros eléctricos',
  'Modelo Base': 'Serie E1 / E2',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '3 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8610',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Arrancadores y tableros configurables',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'FLOWMAK',
  'Línea de Producto': 'Bombas agrícolas, periféricas y sumergibles/ válvulas',
  'Modelo Base': 'VARIOS',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8611',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Uso agrícola y domiciliario',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'MAC3',
  'Línea de Producto': 'Sensores de nivel',
  'Modelo Base': 'Sin modelo definido',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.47,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8612',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'control de nivel',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'RAIN',
  'Línea de Producto': 'Válvulas solenoides, programadores',
  'Modelo Base': 'VARIOS',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8612',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Controladores de riego y electroválvulas',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'KOSLAN',
  'Línea de Producto': 'Tableros eléctricos electronicos',
  'Modelo Base': 'DOMINO / SIMPLEX / DUPLEX',
  'Procedencia': 'Chile',
  '% Desc. Proveedor': 0.38,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8613',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Tableros armados a medida',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'ZENIT',
  'Línea de Producto': 'Bombas aguas servidas industriales',
  'Modelo Base': 'GRBLUE / GRS /GRG / AP / UNIQA',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.45,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8614',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Bombas trituradoras y de canal abierto',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'FLOWMAK',
  'Línea de Producto': 'Generadores',
  'Modelo Base': 'Sin modelo definido',
  'Procedencia': 'No informado',
  '% Desc. Proveedor': 0.5,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '3 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8611',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5674',
  'Datos APP': 'generadores',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'Sin marca definida',
  'Línea de Producto': 'Motobombas',
  'Modelo Base': 'Sin modelo definido',
  'Procedencia': 'No informado',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '1 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8612',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5675',
  'Datos APP': 'motobombas',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'FLOWMAK',
  'Línea de Producto': 'Herramientas',
  'Modelo Base': 'Sin modelo definido',
  'Procedencia': 'No informado',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '0 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8613',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5676',
  'Datos APP': 'herramientas',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'FLOWMAK',
  'Línea de Producto': 'Hidrolavadoras',
  'Modelo Base': 'Sin modelo definido',
  'Procedencia': 'No informado',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '0 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '1 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8614',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5677',
  'Datos APP': 'hidrolavadoras',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'VAREM',
  'Línea de Producto': 'Estanques hidroneumáticos',
  'Modelo Base': 'VERTICAL / HORIZONTAL / 10BAR /16BAR',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8615',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Estanques verticales y horizontales certificados',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'LEO',
  'Línea de Producto': 'bombas superficie, bombas solares/ variadores de frecuencia',
  'Modelo Base': 'LVS / LPP /PQ /3ACM /2ACM /AMS',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.45,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8616',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Uso residencial y riego simple',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'LEO',
  'Línea de Producto': ' variadores de frecuencia',
  'Modelo Base': 'PDH30',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.48,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8616',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Uso residencial y riego simple',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KOSLAN',
  'Marca': 'LEO',
  'Línea de Producto': 'Bombas sumergibles',
  'Modelo Base': 'LVS / LPP /PQ /3ACM /2ACM /AMS',
  'Procedencia': 'China',
  '% Desc. Proveedor': 0.47,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App Koslan',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Smith Martinez  / +56 9 3433 8616',
  'Email': 'smartinez@koslan.cl',
  'Web/App proveedor': 'https://wap.koslan.cl/index.php',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Uso residencial y riego simple',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas Superficiales',
  'Modelo Base': 'Grupo Motobomba Emporia PD, CC, HB',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2025',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas Superficiales',
  'Modelo Base': 'Grupo Motobomba Emporia CP, GS, GC, GR',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2026',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Multietapas Verticales',
  'Modelo Base': 'Grupo Motobomba MOVITEC B, C',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2027',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas Normalizadas',
  'Modelo Base': 'MegaNorm',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2028',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Alta Eficiencia',
  'Modelo Base': 'Motores IE3 B3',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2029',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Premium IE4/IE5',
  'Modelo Base': 'SupremE',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2030',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Automatización',
  'Modelo Base': 'Pumpdrive R, Pumpdrive 2',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.52,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2031',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Agua Residual',
  'Modelo Base': 'Amarex N / ARX / KRT',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.52,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2032',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Accesorios de Montaje',
  'Modelo Base': 'Flanges y Bases',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.28,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9269',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2033',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Agua Residual',
  'Modelo Base': 'Amarex N / ARX / KRT',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.52,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9270',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2034',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Agua Residual',
  'Modelo Base': 'Clas / Clasvort / Drain Vort / Canal Bi',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9271',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2035',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Automatización',
  'Modelo Base': 'Pumpdrive R / Pumpdrive 2',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.52,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9272',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2036',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Automatización',
  'Modelo Base': 'Hyamat V / PD / SPD',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.28,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9273',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2037',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Automatización',
  'Modelo Base': 'Delta Compact / Solo / Primo / Eco',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.52,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9274',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2038',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Válvulas Industriales',
  'Modelo Base': 'ECOLINE / PROFIT / HERA / SYSTO',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9275',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2039',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Accesorios',
  'Modelo Base': 'Flanges / Bases / Camisas / Cables',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.28,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9276',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5678',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2040',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas Monobloc',
  'Modelo Base': 'Megabloc',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9277',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5679',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2041',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Eléctricos',
  'Modelo Base': 'IE3 B3',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9278',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5680',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2042',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Eléctricos',
  'Modelo Base': 'IE3 JM - Movitec',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9279',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5681',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2043',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Rebobinables',
  'Modelo Base': 'UMA / UMC / UMA S',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9280',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5682',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2044',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Motores Encapsulados',
  'Modelo Base': 'COM / CWM / PD / PDM',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.24,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9281',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5683',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2045',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas de Pozo',
  'Modelo Base': 'UPA 200 / 250 / 300 / 350',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.54,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9282',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5684',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2046',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Bombas de Pozo',
  'Modelo Base': 'Upachrom 75 CN / 100 CN / 150 CC / 200 CC',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.62,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9283',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5685',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2047',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'KSB',
  'Marca': 'KSB',
  'Línea de Producto': 'Hidroneumáticos / Accesorios',
  'Modelo Base': 'Hidroneumáticos + kits / Acoplamientos / Cables',
  'Procedencia': 'Alemania',
  '% Desc. Proveedor': 0.57,
  'Forma de Pago': 'No informado',
  'Condición de pago por monto': 'No informado',
  'Garantía': '2 años',
  'Buscar Precio en': 'App KSB',
  'Entrega con despacho': '2 días habiles',
  'Contacto Vendedor': 'Danny Fuenmayor / +56 9 7451 9284',
  'Email': 'Danny.Fuenmayor@ksb.com',
  'Web/App proveedor': 'https://my.ksb.cl/login.jhtm?noMessage=t&forwardAction=https://my.ksb.cl/product.jhtm?id=1768&cid=',
  'Teléfono Oficina': '+56 2 1234 5686',
  'Datos APP': 'Usuario: kgonzalez@grupoproservices.cl / Clave: KIMBGON2048',
  'Instrucción de cotización': 'N/D',
  'Stock': 'N/D'},
 {'Proveedor': 'COSMOPLAS',
  'Marca': 'PENTAX',
  'Línea de Producto': 'Bombas periféricas',
  'Modelo Base': 'PM45 / CB / CBM / CAM',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 0.51,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por WhatsApp o correo al vendedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Carlos Gómez / +56 9 5343 2057',
  'Email': 'cagomez@cosmoplas.com',
  'Web/App proveedor': 'https://cosmoplas.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Catálogo largo, enviar código',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'COSMOPLAS',
  'Marca': 'CNP',
  'Línea de Producto': 'Bombas multietapas / centrífugas',
  'Modelo Base': 'CHLF / CDLF / ZS 50-32-160',
  'Procedencia': 'China',
  '% Desc. Proveedor': 'Cotizar (valor final vía vendedor)',
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por WhatsApp o correo al vendedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Carlos Gómez / +56 9 5343 2057',
  'Email': 'cagomez@cosmoplas.com',
  'Web/App proveedor': 'https://cosmoplas.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Catálogo largo, enviar código',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'COSMOPLAS',
  'Marca': 'VAREM',
  'Línea de Producto': 'Estanques hidroneumáticos / sanitarios',
  'Modelo Base': '24L, 60L, 100L, 200L',
  'Procedencia': 'Italia',
  '% Desc. Proveedor': 'Cotizar (valor final vía vendedor)',
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por WhatsApp o correo al vendedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Carlos Gómez / +56 9 5343 2057',
  'Email': 'cagomez@cosmoplas.com',
  'Web/App proveedor': 'https://cosmoplas.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Catálogo largo, enviar código',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Kit bomba + motor (completo)',
  'Modelo Base': 'Serie SS 4", 6", 8", 10", Fhoton, SubDrive',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.5,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Catálogo Franklin PDF Nov 2024',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Motores y bombas por separado',
  'Modelo Base': 'Motores 4", 6", 8", partes hidráulicas',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.45,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Cotizar código exacto vía WhatsApp',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Sistemas de bombeo solar',
  'Modelo Base': 'Fhoton SolarPAK / SubDrive SolarPAK',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.5,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Ingresar código del kit',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Motores sumergibles encapsulados',
  'Modelo Base': 'Motores 4", 6", 8" encapsulados NEMA',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 0.45,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar parte exacta a cotizar',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Estanques hidroneumáticos',
  'Modelo Base': 'Acero pintado 24L, 60L, 100L, 200L',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 'Cotizar (valor final vía vendedor)',
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Confirmar SKU con vendedor',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'FRANKLIN',
  'Marca': 'Franklin',
  'Línea de Producto': 'Accesorios',
  'Modelo Base': 'Tableros, conectores, protecciones, sellos',
  'Procedencia': 'EE.UU.',
  '% Desc. Proveedor': 'Cotizar (valor final vía vendedor)',
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Por catálogo del proveedor',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Enzo Garrido / +56 9 3262 2274',
  'Email': 'franklinchile@fele.com',
  'Web/App proveedor': 'https://franklinwater.cl',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Cotizar con SKU o descripción',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'ESPA',
  'Marca': 'ESPA',
  'Línea de Producto': 'Bombas centrífugas, multietapas, presurización y riego',
  'Modelo Base': 'AQUACONTROL / MULTI / TECNOPRES / PRISMA',
  'Procedencia': 'España',
  '% Desc. Proveedor': 0.4,
  'Forma de Pago': 'Cheques 30 días',
  'Condición de pago por monto': 'sobre 1MM / 2 cheques / sobre 2MM 3 cheques',
  'Garantía': '1 año',
  'Buscar Precio en': 'Lista de precios interna ESPA',
  'Entrega con despacho': '2 días hábiles',
  'Contacto Vendedor': 'ESPA CHILE / +56 2 2903 8000',
  'Email': 'contacto@espachile.cl',
  'Datos APP': 'Consultar lista de precios enviada por el proveedor',
  'Web/App proveedor': 'https://www.espachile.cl'},
 {'Proveedor': 'HCP',
  'Marca': 'HCP',
  'Línea de Producto': 'Aguas Servidas',
  'Modelo Base': 'Serie AF',
  'Procedencia': 'Taiwanesa',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Catálogo PDF + WhatsApp',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Cristóbal Canales / +56 9 8770 7441',
  'Email': 'N/D',
  'Web/App proveedor': 'N/D',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar código del modelo',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'HCP',
  'Marca': 'HCP',
  'Línea de Producto': 'Lodo / Sólidos',
  'Modelo Base': 'Serie LH / LH-C / LH-G / LH-L',
  'Procedencia': 'Taiwanesa',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Catálogo PDF + WhatsApp',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Cristóbal Canales / +56 9 8770 7441',
  'Email': 'N/D',
  'Web/App proveedor': 'N/D',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar código del modelo',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'HCP',
  'Marca': 'HCP',
  'Línea de Producto': 'Drenaje / Achique',
  'Modelo Base': 'Serie AS / ASP / AL',
  'Procedencia': 'Taiwanesa',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Catálogo PDF + WhatsApp',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Cristóbal Canales / +56 9 8770 7441',
  'Email': 'N/D',
  'Web/App proveedor': 'N/D',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar código del modelo',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'HCP',
  'Marca': 'HCP',
  'Línea de Producto': 'Trituradoras',
  'Modelo Base': 'Serie GR / GT',
  'Procedencia': 'Taiwanesa',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Catálogo PDF + WhatsApp',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Cristóbal Canales / +56 9 8770 7441',
  'Email': 'N/D',
  'Web/App proveedor': 'N/D',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar código del modelo',
  'Stock': 'Confirmar stock'},
 {'Proveedor': 'HCP',
  'Marca': 'HCP',
  'Línea de Producto': 'Contra incendios',
  'Modelo Base': 'Serie FC',
  'Procedencia': 'Taiwanesa',
  '% Desc. Proveedor': 0.3,
  'Forma de Pago': 'Transferencia',
  'Condición de pago por monto': 'contado',
  'Garantía': '1 año',
  'Buscar Precio en': 'Catálogo PDF + WhatsApp',
  'Entrega con despacho': 'No informado',
  'Contacto Vendedor': 'Cristóbal Canales / +56 9 8770 7441',
  'Email': 'N/D',
  'Web/App proveedor': 'N/D',
  'Teléfono Oficina': 'N/D',
  'Datos APP': 'N/D',
  'Instrucción de cotización': 'Enviar código del modelo',
  'Stock': 'Confirmar stock'}]

df_proveedores = pd.DataFrame(PROVEEDORES)
df_margenes = pd.DataFrame(MARGENES)

# =================================================================================
# FUNCIONES
# =================================================================================
def calcular_margen(precio_lista):
    """Determina el margen Proservices según el precio de lista."""
    precio_lista = round(float(precio_lista))
    for _, row in df_margenes.iterrows():
        if row["Min"] <= precio_lista <= row["Max"]:
            return float(row["Margen"])
    return float(df_margenes["Margen"].iloc[-1])


def valor_valido(valor):
    """True cuando existe un valor útil para mostrar."""
    if valor is None:
        return False
    if isinstance(valor, float) and pd.isna(valor):
        return False
    return str(valor).strip() not in ["", "N/D", "nan", "None", "No informado"]


def descuento_numerico(valor):
    """Convierte un descuento válido a decimal. Retorna None si debe cotizarse."""
    if isinstance(valor, (int, float)) and not pd.isna(valor):
        return float(valor)
    return None


def generar_link_contacto(producto):
    """Genera enlace de WhatsApp cuando corresponde; si no, usa email."""
    contacto = producto.get("Contacto Vendedor", "")
    forma = str(producto.get("Buscar Precio en", ""))

    if valor_valido(contacto) and "WhatsApp" in forma:
        texto = str(contacto)
        if "+" in texto:
            numero = texto.split("+")[-1]
            numero = "".join(c for c in numero if c.isdigit())
            if numero:
                return f"https://wa.me/{numero}"

    email = producto.get("Email")
    if valor_valido(email):
        return f"mailto:{email}"

    return None


def obtener_web(producto):
    valor = producto.get("Web/App proveedor")
    return valor if valor_valido(valor) else None


def texto_seguro(producto, campo, defecto="No informado"):
    valor = producto.get(campo)
    return str(valor) if valor_valido(valor) else defecto


# =================================================================================
# INTERFAZ
# =================================================================================
st.title("📊 Cotizador Grupo Proservices By Rodrigo Muñoz")
st.markdown("---")

with st.sidebar:
    st.header("🔍 Filtros")

    proveedor = st.selectbox(
        "Proveedor",
        df_proveedores["Proveedor"].dropna().unique()
    )

    marcas = (
        df_proveedores[df_proveedores["Proveedor"] == proveedor]["Marca"]
        .fillna("Sin marca definida")
        .astype(str)
        .unique()
    )
    marca = st.selectbox("Marca", marcas)

    filtro_marca = df_proveedores[
        (df_proveedores["Proveedor"] == proveedor) &
        (df_proveedores["Marca"].fillna("Sin marca definida").astype(str) == marca)
    ]

    lineas = (
        filtro_marca["Línea de Producto"]
        .fillna("Sin línea definida")
        .astype(str)
        .unique()
    )
    linea = st.selectbox("Línea de Producto", lineas)

    productos_filtrados = filtro_marca[
        filtro_marca["Línea de Producto"].fillna("Sin línea definida").astype(str) == linea
    ]

    if len(productos_filtrados) > 1:
        modelos = (
            productos_filtrados["Modelo Base"]
            .fillna("Sin modelo definido")
            .astype(str)
            .tolist()
        )
        modelo_seleccionado = st.selectbox("Modelo / Serie", modelos)

        producto = productos_filtrados[
            productos_filtrados["Modelo Base"]
            .fillna("Sin modelo definido")
            .astype(str) == modelo_seleccionado
        ].iloc[0].to_dict()
    else:
        producto = productos_filtrados.iloc[0].to_dict()


st.subheader(
    f"📦 {texto_seguro(producto, 'Marca', 'Sin marca definida')} - "
    f"{texto_seguro(producto, 'Línea de Producto', 'Sin línea definida')}"
)

col1, col2 = st.columns(2)

with col1:
    st.markdown("### 📋 Especificaciones")

    st.write(f"**Proveedor:** {texto_seguro(producto, 'Proveedor')}")
    st.write(f"**Modelo:** {texto_seguro(producto, 'Modelo Base', 'Sin modelo definido')}")
    st.write(f"**Procedencia:** {texto_seguro(producto, 'Procedencia')}")
    st.write(f"**Garantía:** {texto_seguro(producto, 'Garantía')}")
    st.write(f"**Forma de pago:** {texto_seguro(producto, 'Forma de Pago')}")

    condicion_pago = producto.get("Condición de pago por monto")
    if valor_valido(condicion_pago):
        st.write(f"**Condición de pago:** {condicion_pago}")

    contacto = texto_seguro(producto, "Contacto Vendedor")
    contacto_link = generar_link_contacto(producto)

    if contacto_link:
        st.markdown(f"**Contacto:** [📩 {contacto}]({contacto_link})")
    else:
        st.write(f"**Contacto:** {contacto}")

    web_proveedor = obtener_web(producto)
    if web_proveedor:
        st.markdown(f"🌐 **Sitio del proveedor:** [Abrir]({web_proveedor})")

    buscar_precio = producto.get("Buscar Precio en")
    if valor_valido(buscar_precio):
        st.write(f"**Buscar precio en:** {buscar_precio}")

    instruccion = producto.get("Instrucción de cotización")
    if valor_valido(instruccion):
        st.write(f"**Instrucción de cotización:** {instruccion}")

    stock = producto.get("Stock")
    if valor_valido(stock):
        st.write(f"**Stock:** {stock}")

    datos_app = producto.get("Datos APP")
    if valor_valido(datos_app):
        st.markdown(f"🔑 **Datos de acceso:** {datos_app}")


with col2:
    st.markdown("### 💵 Precios")

    precio_lista = st.number_input(
        "Precio de lista (CLP):",
        min_value=0,
        step=1000
    )

    if precio_lista > 0:
        descuento_proveedor = descuento_numerico(
            producto.get("% Desc. Proveedor")
        )

        st.markdown("### 🧾 Resumen de Cotización")
        st.info(
            f"**Precio de lista (ingresado por el usuario):** "
            f"${precio_lista:,.0f} CLP"
        )

        if descuento_proveedor is None:
            st.warning(
                "**Descuento del proveedor:** Cotizar valor final con vendedor. "
                "No se calcula automáticamente el costo ni el precio de venta."
            )
        else:
            # ÚNICO descuento aplicado: descuento normal del proveedor.
            precio_final = precio_lista * (1 - descuento_proveedor)

            # El margen se define por el PRECIO DE LISTA, no por el costo.
            margen = calcular_margen(precio_lista)

            # Margen real sobre precio de venta.
            precio_venta = precio_final / (1 - margen)

            # Diferencia entre precio lista y precio sugerido.
            descuento_visible = 1 - (precio_venta / precio_lista)

            st.info(
                f"**Porcentaje de descuento del proveedor:** "
                f"{descuento_proveedor * 100:.2f}%"
            )

            st.success(
                f"**Costo del producto (con descuento proveedor):** "
                f"${precio_final:,.0f} CLP"
            )

            st.success(
                f"**Margen de ganancia Proservices aplicado:** "
                f"{margen * 100:.1f}%"
            )

            st.success(
                f"**Precio de venta sugerido (neto al cliente):** "
                f"${precio_venta:,.0f} CLP"
            )

            if descuento_visible >= 0:
                st.error(
                    f"**Descuento a mostrar en la cotización:** "
                    f"{descuento_visible * 100:.2f}%"
                )
            else:
                st.warning(
                    f"**Precio sugerido sobre precio de lista:** "
                    f"{abs(descuento_visible) * 100:.2f}%"
                )


with st.sidebar:
    st.markdown("### 📊 Márgenes 2026")

    fig, ax = plt.subplots(figsize=(5, 3))
    ax.bar(
        df_margenes["Tramo"],
        df_margenes["Margen"] * 100,
        color="#4CAF50"
    )
    ax.set_ylabel("Margen (%)")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    st.pyplot(fig)


st.markdown("---")
st.markdown(
    f"**Proservices** - © {datetime.now().year} | "
    "Versión GrupoProservices by Rodrigo Muñoz 2026"
)


